--- #YAML:1.0
name:               CatalystX-CRUD-ModelAdapter-DBIC
version:            0.11
abstract:           CRUD for Catalyst::Model::DBIC::Schema
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Model::DBIC::Schema:  0
    CatalystX::CRUD:      0.42
    Data::Dump:           0
    DBIx::Class:          0
    DBIx::Class::RDBOHelpers:  0.04
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
