# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CatalystX-CRUD-ModelAdapter-DBIC
version:      0.04
version_from: lib/CatalystX/CRUD/ModelAdapter/DBIC.pm
installdirs:  site
requires:
    Catalyst::Model::DBIC::Schema: 0
    CatalystX::CRUD:               0.29
    DBIx::Class:                   0
    DBIx::Class::RDBOHelpers:      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
